# Generated by Django 2.2.28 on 2023-03-06 16:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='outcome',
            name='image',
            field=models.ImageField(blank=True, upload_to='outcome_images'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
