# Generated by Django 2.2.28 on 2023-03-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20230309_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
    ]
