# Generated by Django 2.2.28 on 2023-03-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
