# Generated by Django 2.2.28 on 2023-03-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20230307_2124'),
        ('quiz', '0007_auto_20230309_2040'),
    ]

    operations = [
    ]
