# Generated by Django 2.2.28 on 2023-03-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20230311_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_outcomes',
            field=models.IntegerField(default=0, verbose_name='Number of outcomes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='num_questions',
            field=models.IntegerField(default=0, verbose_name='Number of questions'),
        ),
    ]
