# Generated by Django 2.2.28 on 2023-03-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20230311_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='num_outcomes',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='num_questions',
        ),
    ]
