# Generated by Django 2.2.28 on 2023-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20230312_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='image',
            field=models.ImageField(upload_to='outcome_images'),
        ),
    ]
