# Generated by Django 2.2.28 on 2023-03-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20230312_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='index',
            field=models.IntegerField(verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='index',
            field=models.IntegerField(verbose_name='index'),
        ),
    ]
