# Generated by Django 2.2.28 on 2023-03-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20230314_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures'),
        ),
    ]
